### ISSUE TITLE
"Load File" directory traversal should sort entries alphabetically

### ISSUE THREAD

**Issue by ell1e** [rohanrhu/gdb-frontend#12]
"Load File" directory traversal should sort entries alphabetically. Right now it seems to be completely random making it kind of unusable:

![Screenshot from 2020-10-08 09-28-44](https://user-images.githubusercontent.com/64124388/95428027-fb5d9e80-0937-11eb-8324-6211c712ad49.png)

**Comment by rohanrhu** [comment]
Added a JavaScript sort. (https://github.com/rohanrhu/gdb-frontend/commit/cdb562c7292c684cc31635ee48e1de2197b2f74e)

**Comment by ell1e** [comment]
Is it already supposed to show up as sorted with the latest git version? Sadly, it still seems to be mixed up even though I can see that added `.sort()` line when I browse in Inspect mode into FileBrowser.js

**Comment by rohanrhu** [comment]
It must be solved with https://github.com/rohanrhu/gdb-frontend/commit/6cc9fff73be12f87317aa0f12bc46a037a7a3a30

**Comment by ell1e** [comment]
It works now, very nice work :blush:  :+1:
