### ISSUE TITLE
Suggestion: clicking the "run" icon (the bug that will start the debugging) should show up a dialog to prompt me for command line arguments with "Run", "Cancel" buttons instead of running directly

### ISSUE THREAD

**Issue by ell1e** [rohanrhu/gdb-frontend#14]
I discovered that clicking the "Run" icon (the bug that will start the debugging) just starts the program directly. However, I am debugging a compiler, so I need to submit arguments to it so it'll actually compile the test file instead of just quit instantly. I think the most natural way to do that would be if clicking that "Run" icon just prompted me with a popup dialog with run options like command line arguments, environment vars, etc with "Run", "Cancel" buttons to confirm and actually run and cancel out, respectively.

Alternatively, adding a "Launch Options" entry to the top-right hamburger menu icon would also be a good way where people could find & edit this, if you really don't want the "Run" icon to require one additional click to confirm to actually fully run it. (Which I suppose would be an understandable objection)

Or you could prompt for this when using "Load File" to open an executable initially, although then there should probably still be a "Launch Options" entry accessible from somewhere to easily modify it later.

**Comment by rohanrhu** [comment]
Hi, thank you for feedback. I will add a menu for setting run arguments. For now, you can use `run [arguments..]` command on GDB shell. (Once you use args in run commands, it remembers args in future runs with run button.)

**Comment by ell1e** [comment]
Ah, cool! Thanks, that sounds very useful @ remembering the args on future runs

**Comment by rohanrhu** [comment]
I added run arguments setting for run button.

![runargs](https://user-images.githubusercontent.com/1125150/95758416-20903b00-0cb1-11eb-860d-59342938c45e.png)
