### ISSUE TITLE
(Not sure if bug?) Opening a .c file will sometimes not actually open it as a source code file tab

### ISSUE THREAD

**Issue by ell1e** [rohanrhu/gdb-frontend#16]
In the project of mine I'm trying to debug, when I open a specific .c file via "Load File" then instead of showing up as an additional source code tab (which is what I wanted) instead the tree view disappears. It almost seems like gdb-frontend thought it was a binary, but it is not - it's really just a very boring text file. Am I supposed to open source files via some other button, or is that a bug? In any case, it'd be cool if "Load File" actually detected a code file vs a binary and magically did "the right thing" for both which at least for this case doesn't seem to have worked out.

Here is the issue in a short clip where I open the .c file:

![output](https://user-images.githubusercontent.com/64124388/95609597-7618dd80-0a4e-11eb-979d-7f9aa6e6cfd3.gif)

**Comment by rohanrhu** [comment]
"Load File" button is different from the load icon in right side of "Sources" section title.

* "Load File" button is for loading executables.
* Sources --- Load icon is for opening any file in editor.

**Comment by ell1e** [comment]
Maybe you should rename it to "Load Executable" then? Might also be worth finding some way to filter the file list to only executables one day (e.g. by probing the header of the listed files for ELF and other common formats)

**Comment by rohanrhu** [comment]
Good idea. Renamed it to "Load Executable". Thank you for feedback. I will change icon also.

**Comment by ell1e** [comment]
You are so quick :heart_eyes: :+1:

**Comment by rohanrhu** [comment]
By the way, when you add breakpoint a line in `main()` and step over the line for first time, you will see all sources on the left side and you can use Ctrl+P fuzzy finder also.

It seems also we have a scrollbar style problem for Firefox, I will look to that.
