### ISSUE TITLE
Firefox WebSocket problem

### ISSUE THREAD

**Issue by Waqar144** [rohanrhu/gdb-frontend#17]
Hi,

I tried to run it as mentioned in the readme but I keep getting `"Connection closed to GDBFrontend server!"` alerts in the browser.

**Comment by rohanrhu** [comment]
Hi, can you get the output on GDB shell with `tmux a -t gdb-frontend` command and what are your browser and OS?

**Comment by Waqar144** [comment]
I am running Manjaro Linux and my browser is Firefox 81.

Just tried it with chromium based Falkon and everything seems to be working correctly
