### ISSUE TITLE
pip install-able

### ISSUE THREAD

**Issue by cmurphy208** [rohanrhu/gdb-frontend#20]
If this is pure python, could we not make this pip-installable by adding a setup.py file. It will make adoption and use very easy across all platforms since pip is a part of the python ecosystem itself.

**Comment by rohanrhu** [comment]
Yes. PIP package would be great.

**Comment by rohanrhu** [comment]
I've made PIP package.

You can install GDBFrontend with PIP:
```bash
pip install gdbfrontend
```
