### ISSUE TITLE
gdbinit support

### ISSUE THREAD

**Issue by zzdts** [rohanrhu/gdb-frontend#26]
How to config  GDB when gdb-frontend start ?
It seems  not read .gdbinit file when i have  start with -w option?

**Comment by rohanrhu** [comment]
I've added `--gdb-args="ARGS", -G "ARGS"` option. You can specify your `.gdbinit` with it.

**Comment by VelorumS** [comment]
Note that gdb-frontend sets this:

```
set confirm off
set non-stop off
set pagination off
```

if anyone struggling to understand why their gdbinit isn't working.

What kind of problems the non-stop will cause?

**Comment by rohanrhu** [comment]
> Note that gdb-frontend sets this:
> 
> ```
> set confirm off
> set non-stop off
> set pagination off
> ```
> 
> if anyone struggling to understand why their gdbinit isn't working.

You can still set them after the debugger is booted up.

> What kind of problems the non-stop will cause?

As far as I remember, GDB's non-stop mode is necessary for GDBFrontend's thread to be able to run while your app is running on debugger.
