### ISSUE TITLE
Passing commandline options to gdb

### ISSUE THREAD

**Issue by lukehutch** [rohanrhu/gdb-frontend#28]
I can't see a way to pass commandline arguments to gdb. Can you please add an option for this?

**Comment by rohanrhu** [comment]
https://github.com/rohanrhu/gdb-frontend/issues/26

**Comment by rohanrhu** [comment]
I've added the option.

```
--gdb-args="ARGS", -G "ARGS"
```

**Comment by lukehutch** [comment]
Awesome, thanks!
