### ISSUE TITLE
How to view std::vector contents?

### ISSUE THREAD

**Issue by typon** [rohanrhu/gdb-frontend#32]
Whenever I click on a variable that's a std::vector type, I get the error:

`Structure or union is not initialized yet`

**Comment by rohanrhu** [comment]
I added auto and ptr array support to VariablesExplorer. `std::vector` support is still waiting, I will make it soon. I also will add `std::list` support on LinkedListVisualizer.

I've also made expression connection to support arrays too.

![image](https://user-images.githubusercontent.com/1125150/145752164-348e7bf4-3411-4cde-870c-60d97ca3ec25.png)

**Comment by rohanrhu** [comment]
@typon `std::vector` support is added. Feel free to re-open this issue when you see any issue. 😊

![image](https://user-images.githubusercontent.com/1125150/155809508-fe93ac17-4b5e-4d7c-955e-82384f127242.png)
