### ISSUE TITLE
Python 3.7 is not supported

### ISSUE THREAD

**Issue by RishabhRawat** [rohanrhu/gdb-frontend#36]
The documentation says `Python >= 3.2` is supported, but python 3.7 crashes on - 

https://github.com/rohanrhu/gdb-frontend/blob/4408faa125f3e41af35796563bbdb83762b4f894/api/debug.py#L25
`from typing import final`

might be a good idea to add lint prevent newer python features in the repo if you plan to support older python versions

**Comment by rohanrhu** [comment]
I've removed usage of `typing` module.

Can you try this release?
https://github.com/rohanrhu/gdb-frontend/releases/tag/v0.9.6-beta

**Comment by RishabhRawat** [comment]
That solves the issue, Thank you so much :)

**Comment by rohanrhu** [comment]
> That solves the issue, Thank you so much :)

Nice :)
