### ISSUE TITLE
Is there a way to load gdb-multiarch instead of vanilla gdb?

### ISSUE THREAD

**Issue by kshitej** [rohanrhu/gdb-frontend#4]
Trying this tool for remote debugging an arm board using a x86 computer. Running the ./gdbfrontend command opens an instance of gdb; is there a way to substitute this for gdb-multiarch?

**Comment by rohanrhu** [comment]
Look this: https://github.com/rohanrhu/gdb-frontend#--gdb-executablepath--g-path

You can specify GDB executable like: `./gdbfrontend -g /path/to/gdb`
