### ISSUE TITLE
sorting files in folder in the sources aids the navigation

### ISSUE THREAD

**Issue by grooverdan** [rohanrhu/gdb-frontend#44]
![image](https://user-images.githubusercontent.com/462287/149645115-fd0f66e9-0d84-4859-9733-3fc69b2000ee.png)

Currently this folder contains a lot of files that cannot be searched by name, so having them sorted will make it easier to navigate to a file.

**Comment by rohanrhu** [comment]
Right.... I will do this for next release. Thank youu 😊

**Comment by rohanrhu** [comment]
Btw, there is also a fuzzy finder that opens with **CTRL + P**.

**Comment by rohanrhu** [comment]
Hewwwooo @grooverdan I added alphabetically sorting. You can test it 😊

![image](https://user-images.githubusercontent.com/1125150/156471915-4f96e5df-3713-4375-893e-1ffdffd1de80.png)
