### ISSUE TITLE
Not support risc-v 

### ISSUE THREAD

**Issue by zzdts** [rohanrhu/gdb-frontend#52]
Has any plan to support risc-v arch?

**Comment by zzdts** [comment]
Oh, that's my fault.
I  used  qemu run a riscv program:
`$ qemu-system-riscv64 -M virt -kernel kernel.img -bios none -serial stdio -s -S & `
 `$ gdbfrontend `
So i get  errors: 
_"warning: while parsing target description (at line 1): Target description specified unknown architecture "riscv:rv64""_

If i  specify gdb cmd that support riscv, gdbfrontend works well.
The correct cmd to work with riscv :
`$ gdbfrontend -g /usr/bin/gdb-multiarch`

**Comment by rohanrhu** [comment]
> If i specify gdb cmd that support riscv, gdbfrontend works well. The correct cmd to work with riscv : `$ gdbfrontend -g /usr/bin/gdb-multiarch`

It would be great if you could write a tutorial in `documentation/` or add a quick notice to README.md about the steps you followed to debug RISC-V with QUEMU and GDBFrontend.

`documentation/` directory automatically deploys to https://rohanrhu.github.io/gdb-frontend/.
