### ISSUE TITLE
cannot read file in demo?

### ISSUE THREAD

**Issue by likyh** [rohanrhu/gdb-frontend#54]
```cpp
#include <stdio.h>
int main(){
    int a, b;
    scanf("%d%d", &a, &b);
    printf("%d\n", a+b);
    return 0;
}
```

got:
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/3294100/180632036-dd57d8fb-9fd6-4258-9f9d-66f5c1d3c556.png">

**Comment by rohanrhu** [comment]
When you use `scanf()` and similars, OS sends `SIGTTIN` to your process and GDB shell and your app can't use the same TTY like this. Your app must use a different TTY than the one that your GDB shell is on.

# Simplest way to debug apps that take inputs on TTY

## Split terminal and run your app in new terminal
![image](https://user-images.githubusercontent.com/1125150/180650508-ebbc0bda-2890-4cf6-a3a4-323e5d4e0a77.png)

## Attach GDB to your process
![image](https://user-images.githubusercontent.com/1125150/180650562-d41d1265-b3dd-48e3-8046-ec3dd08e0d12.png)

## When GDB attached to your process, your process will be interrupted immediately, **just click to continue**
![image](https://user-images.githubusercontent.com/1125150/180650630-3a6f82f8-cfc6-46cf-8a18-d7e87c504a70.png)

## Add a breakpoint after the call that gets input from TTY and enter an input and press enter
![image](https://user-images.githubusercontent.com/1125150/180650717-81464009-fb50-486c-a222-af0371f50a9b.png)

That's all.

**Comment by likyh** [comment]
thank you~

**Comment by GitMensch** [comment]
That's very useful - What do you think about adding this to the tutorials and link that in README?

**Comment by rohanrhu** [comment]
> That's very useful - What do you think about adding this to the tutorials and link that in README?

Thank you @GitMensch I will add it to docs and link in README.md.
