### ISSUE TITLE
building gdb on arch failed

### ISSUE THREAD

**Issue by jean-lopes** [rohanrhu/gdb-frontend#58]
Error message: `ld: cannot find -lboost_regex: No such file or directory`

solution: sudo pacman -S boost

Should this dependency be added to: https://github.com/rohanrhu/gdb-frontend/blob/master/build_gdb.sh#L94-L95C30 ? (Also, on other distros?)

**Comment by rohanrhu** [comment]
Hi @jean-lopes, thank you for reporting. I don't have time for it at the moment. Could you add and test it and make a pull request? It would be nice if you could try building on other distros too.

**Comment by rohanrhu** [comment]
Added for all distros. (Debian, Ubuntu, Arch)
