### ISSUE TITLE
Accessing debugger interface from another machine (Access is denied)

### ISSUE THREAD

**Issue by Tiang-88** [rohanrhu/gdb-frontend#59]
[Running From GIT](https://github.com/rohanrhu/gdb-frontend#running-from-git)
You can download latest source and run it.

You can run gdb-frontend with following commands:

git clone https://github.com/rohanrhu/gdb-frontend.git gdb-frontend
cd gdb-frontend
./gdbfrontend
and you can open it with:

http://127.0.0.1:5550/

root@iZ2ze4kh3gm5ikdfnd4oz7Z:/www/wwwroot/ceshi/gdb-frontend# ./gdbfrontend
GDBFrontend v0.11.4-git
Listening on 127.0.0.1: http://127.0.0.1:5550/
Open this address in web browser: http://127.0.0.1:5550/

**Comment by rohanrhu** [comment]
If you are trying to reach from another machine, you should set the TCP bind address.

```bash
./gdbfrontend -l 0.0.0.0
```

Then you can access the debugger interface from:

```
http://your_devices_local_address:5550/
```
