### ISSUE TITLE
Evaluating pointers as arrays

### ISSUE THREAD

**Issue by NanShanJi** [rohanrhu/gdb-frontend#64]
![image](https://github.com/rohanrhu/gdb-frontend/assets/29830173/628fb2ce-38bd-4357-b255-ef1067e05d09)

Hello, it seems that it does not support the display of pointer array values

**Comment by rohanrhu** [comment]
Hi, you can evaluate and show pointers as array.

Open a new evaluator (𝑓𝑥 button on the top bar) and cast your pointer into an array like this:

```c
*argv@2
```

The syntax is `*ptr@NUM_OF_ITEMS`.

![image](https://github.com/rohanrhu/gdb-frontend/assets/1125150/67e1af9c-e3bd-4a5e-9949-80c3d6abdb7e)

(The first evaluator window is a pointer evaluated and you can't see it as an array but the second one it is casted into an array.)

GDB doesn't know that how many items there are on the memory from the address your pointer is pointing; so you convert it into an array like this with a length.
