### ISSUE TITLE
How can I change the host and port of gdbfrontend?

### ISSUE THREAD

**Issue by borisu** [rohanrhu/gdb-frontend#7]
This is somewhat very basic, but cannot fiigure it out apart from changing the code of config.py .
However seams like 127.0.0.1 is hard coded on may levels.

Any trick to bind the server on 0.0.0.0  and different port?

**Comment by rohanrhu** [comment]
Thank you for feedback. I will add new options for port and listening address.

**Comment by rohanrhu** [comment]
Added new options: https://github.com/rohanrhu/gdb-frontend#--listenip--l-ip
