### ISSUE TITLE
Live Demo SSL Cert Warning

### ISSUE THREAD

**Issue by silentwarble** [rohanrhu/gdb-frontend#71]
Just a heads up the link in "[Try it online!](https://debugme.dev/)" from the README throws a cert error because mismatched CN name.

![image](https://github.com/user-attachments/assets/26d4bb5d-bac3-45b8-9b82-382298cb29df)

**Comment by rohanrhu** [comment]
Hi, actually I've closed debugme.dev, it must be removed from the README.md.

It was a running instance of [GDBFrontendLive](https://github.com/rohanrhu/gdb-frontend-live). You can use it if you want but it is hard and complicated to make safe to public publicly.

**Comment by silentwarble** [comment]
All good, just an fyi for you. Thanks!
