### ISSUE TITLE
Debugging without debug symbols

### ISSUE THREAD

**Issue by pawlos** [rohanrhu/gdb-frontend#9]
I've tried to use GDB frontend on Ubuntu running in WSL. I can start it buf if I want to use the UI in the browser I'm getting either 'Path not found' or 'An error occured'.

Cmd to run gdbfrontend:

     gdbfrontend --verbose --workdir=/c/temp/ctf/ropemporium/task-write4

Inside gdbfrontend:
    
    file ./write4
    break main
    r

After that - click on stack frame gives me this:
![image](https://user-images.githubusercontent.com/1296768/85117098-99f5b080-b21e-11ea-83bc-7b3f85916015.png)

Click on any fine in the source on the left side gives this:

![image](https://user-images.githubusercontent.com/1296768/85117118-a2e68200-b21e-11ea-9505-a5e5c1bbc886.png)

Am I doing something wrong here?

**Comment by rohanrhu** [comment]
Is there any output in GDB shell? You can access GDB shell with `http://127.0.0.1:5551/terminal/` or `tmux a -t gdb-frontend`.

**Comment by pawlos** [comment]
Not much really (at least nothing that would scream error). 

https://gist.github.com/pawlos/d3e7c66b7bf085cf756669e9a410daf6

**Comment by rohanrhu** [comment]
> Not much really (at least nothing that would scream error).
> 
> https://gist.github.com/pawlos/d3e7c66b7bf085cf756669e9a410daf6

It says `Reading symbols from ./write4...(no debugging symbols found)...done.` Is the executable compiled with gcc's `-g` option with WSL gcc?

You can compile and link executables with debug symbols like: `gcc -o executable executable.c -g`

**Comment by pawlos** [comment]
Yeah, there's no source as it's not even compiled by me but if source not present I was expecting to see some disassembly. I cannot use gdbfrontend w/o source code to see disassm? Is it only working with source code?

**Comment by rohanrhu** [comment]
Yes for now. I will add a disassembly tab/view in addition to disassembly view on the right side. It is a TODO.

For frames, I think there is an issue about no source on switching frames. I will fix it for displaying frame address instead of source file/line and fix switching problem for no source situtiations. When it is fixed we will able to seeing registers for each frame for no source situtiations.

There is no a registers view but you can watch registers with adding registers like `$register` to watches view. (Example: `$rax`)

**Comment by rohanrhu** [comment]
I added debugging without debug symbols support and improved something. After testing, I will release a new version. You can try last revision (https://github.com/rohanrhu/gdb-frontend/commit/695acd43e894b0a2d748008abe75c4f85c71f26c) and tell me if it is ok or is there any error.

**Comment by pawlos** [comment]
It works :)

Additional observations, in the call stack, after clicking on __libc_start_main() there's an error that cannot find source, but after dismissing it the disassembly shows up correctly - not sure if an error is needed (guess depending on user needs?). In the terminal the following errors are present:

https://gist.github.com/pawlos/7592b0a4fb11dab6d5110105e17d4bd6

Note, it was gdb with pwndbg so there might be some interference. Later I can check without pwndbg.

**Comment by rohanrhu** [comment]
Missing source errors dont repeat for same sources no longer.

Does that errors cause a problem as functionality? I will add a behaviour to ignore it.

**Comment by pawlos** [comment]
Nope, looks like everything works as expected but I'll test a bit more in the upcoming days.

**Comment by rohanrhu** [comment]
Ignored that errors. https://github.com/rohanrhu/gdb-frontend/commit/8a94938902d2818892273e4a62f79ebeda053b93
